In [1]:
import numpy as np

In [2]:
myarr = np.array([[1,2,3,4]])
myarr

array([[1, 2, 3, 4]])

In [3]:
myarr.shape

(1, 4)

In [4]:
myarr.dtype

dtype('int64')

In [5]:
myarr[0,1] = 45

In [6]:
myarr

array([[ 1, 45,  3,  4]])

***array creation : conversion form other python structures***

In [7]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
listarray.shape

(3, 3)

In [10]:
listarray.dtype

dtype('int64')

In [11]:
listarray.size

9

***Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc).***

In [12]:
zeros = np.zeros((3,3))

In [13]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
ang = np.arange(14)

In [15]:
ang

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [16]:
lspace = np.linspace(1,100,10)

In [17]:
lspace

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [18]:
emty = np.empty((4,5))

In [19]:
emty

array([[6.23042070e-307, 2.22523004e-307, 4.45055939e-308,
        9.34602321e-307, 6.23054972e-307],
       [1.78021527e-306, 1.33511290e-306, 1.11258854e-306,
        1.11261502e-306, 1.42410839e-306],
       [7.56597770e-307, 6.23059726e-307, 1.42419530e-306,
        1.11261027e-306, 1.06809996e-306],
       [1.37962456e-306, 1.29060871e-306, 1.29061414e-306,
        1.42410974e-306, 5.97819431e-322]])

In [20]:
emty_like = np.empty_like(lspace)

In [21]:
emty_like

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [22]:
idn = np.identity(45)

In [23]:
idn

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [24]:
idn.shape

(45, 45)

In [25]:
arn = np.arange(99)

In [26]:
arn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
arn.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [28]:
arn = arn.ravel()

In [29]:
arn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
arn.shape

(99,)

In [31]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [32]:
arr = np.array(x)

In [33]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr.sum(axis = 0)   ### ager axis zero rakha ga to wo coloumn ko add kra ga

array([12, 15, 18])

In [35]:
arr.sum(axis = 1)   ### ager axis one rakha ga to wo row ko add kra ga

array([ 6, 15, 24])

In [36]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [37]:
arr.flat

In [38]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [39]:
one = np.array([1,2,3,44])


In [40]:
one

array([ 1,  2,  3, 44])

In [41]:
one.argmax()

np.int64(3)

In [42]:
one.argmin()

np.int64(0)

In [43]:
one.argsort()

array([0, 1, 2, 3])

In [44]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr.argmax(axis = 0)

array([2, 2, 2])

In [46]:
arr.argmax(axis = 1)


array([2, 2, 2])

In [47]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [48]:
x = np.array([[1,2,3],[4,5,9],[7,4,4]])

In [49]:
x

array([[1, 2, 3],
       [4, 5, 9],
       [7, 4, 4]])

In [50]:
arr + x

array([[ 2,  4,  6],
       [ 8, 10, 15],
       [14, 12, 13]])

In [51]:
arr * x

array([[ 1,  4,  9],
       [16, 25, 54],
       [49, 32, 36]])

In [52]:
np.sin(12)

np.float64(-0.5365729180004349)

In [54]:
np.cos(123)

np.float64(-0.8879689066918555)

In [55]:
np.tan(2)

np.float64(-2.185039863261519)